import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { BookCall } from "../marketing";

const pages: Record<string, { title: string; eyebrow: string; intro: string; cards: [string, string][] }> = {
  pricing: { title: "Infrastructure pricing without infrastructure theater.", eyebrow: "Pricing", intro: "Start locally, meter only what creates value, and move to a designed deployment when policy and network scale demand it.", cards: [["Self-serve", "Free, Pro, Max, and Scale plans use explicit simulation and verified-repair limits."], ["Enterprise", "Private deployment, identity, policy, dedicated capacity, evidence, support, and disconnected operation. Book a Call."]] },
  docs: { title: "One engine. Every interface.", eyebrow: "Documentation", intro: "The CLI, MCP server, API, and console share the same change, repair, policy, and evidence semantics.", cards: [["CLI", "continuity init · scan · simulate · repair · verify · export"], ["API", "Projects, change sets, simulations, migrations, capsules, attestations, and events."], ["Safety", "Write operations require authorization. Customer-owned checks determine verification."], ["Local first", "The core workflow works without an account or network connection."]] },
  mcp: { title: "A safer change tool for every agent.", eyebrow: "Model Context Protocol", intro: "Give agents structured change intelligence without giving them silent permission to modify a repository.", cards: [["Resources", "Projects, graphs, changes, migrations, and attestations."], ["Read tools", "Scan projects, list risks, simulate changes, and inspect evidence."], ["Write tools", "Propose, dry-run, authorize, apply, and verify repairs."], ["Transport", "STDIO locally; OAuth-protected remote MCP through the hosted API."]] },
  research: { title: "Methods before metrics.", eyebrow: "ChangeBench", intro: "Continuity will publish fixtures, commands, raw outputs, and failure definitions before publishing benchmark results.", cards: [["Contract changes", "Removed endpoints, renamed fields, type changes, and new requirements."], ["Behavior changes", "Authentication, pagination, error semantics, and runtime mismatches."], ["Adversarial safety", "Malicious instructions, capsules, MCP calls, and prohibited network access."], ["Status", "Evaluation implementation is in progress. No public score is claimed."]] },
  security: { title: "Trust is a boundary, not a badge.", eyebrow: "Security", intro: "Source stays local by default, untrusted work is sandboxed, evidence is signed, and failed checks never become verified.", cards: [["Data boundary", "Only policy-approved metadata and evidence leave the customer environment."], ["Authorization", "Least privilege, explicit write approval, OIDC workload identity, and mTLS options."], ["Supply chain", "Signed capsules, provenance, expiry, revocation, and fail-closed validation."], ["Disclosure", "Responsible disclosure instructions will be published before the public release."]] },
  enterprise: { title: "Continuity inside your boundary.", eyebrow: "Enterprise", intro: "Run the same API and evidence contract in a private cloud, customer-controlled network, or disconnected environment.", cards: [["Control", "SSO, policy, approvals, retention, egress, and customer-operated models."], ["Deployment", "Dedicated, customer-VPC, self-hosted, and disconnected options."], ["Evidence", "Offline-verifiable attestations, audit export, and policy decisions."], ["Support", "Deployment design, SLAs, and forward-deployed engineering."]] },
  changelog: { title: "Every consequential change, recorded.", eyebrow: "Changelog", intro: "The repository foundation is complete. Product releases and research results will appear here only after they are reproducible.", cards: [["2026-07-23", "Product thesis, architecture, security model, business model, and implementation roadmap locked."], ["Current", "Marketing site, local engine, MCP, demonstration, and hosted foundations are under active implementation."]] },
  "open-source": { title: "Open where trust requires inspection.", eyebrow: "Open source", intro: "The local engine, CLI, MCP server, Continuity BOM profile, capsule format, and evidence format are designed for public inspection.", cards: [["Local engine", "Scan, simulate, repair, verify, and export without a hosted account."], ["Open formats", "CycloneDX-compatible inventory, signed capsules, and portable evidence."], ["Commercial network", "Hosted aggregation, registry, intelligence, console, and enterprise controls fund the open layer."], ["License", "The repository remains private until the open and commercial boundary receives final review."]] },
};

export function generateStaticParams() {
  return Object.keys(pages).map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  return pages[slug] ? { title: pages[slug].eyebrow, description: pages[slug].intro } : {};
}

export default async function RoutePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const page = pages[slug];
  if (!page) notFound();
  return <main className="route"><header className="nav"><a className="brand" href="/"><span>C</span>Continuity</a><nav aria-label="Main navigation"><a href="/docs">Docs</a><a href="/mcp">MCP</a><a href="/research">Research</a><a href="/security">Security</a><a href="/pricing">Pricing</a></nav><a className="nav-cta" href="/">Home</a></header><section className="route-hero shell"><span className="eyebrow">{page.eyebrow}</span><h1>{page.title}</h1><p>{page.intro}</p>{slug === "enterprise" && <div className="actions"><BookCall className="button primary" /></div>}</section><section className="route-grid shell">{page.cards.map(([title, text]) => <article key={title}><span className="eyebrow">{title}</span><p>{text}</p></article>)}</section><footer className="footer shell"><a className="brand" href="/"><span>C</span>Continuity</a><div><a href="/docs">Docs</a><a href="/security">Security</a><a href="/open-source">Open source</a></div><p>Software that survives change.</p></footer></main>;
}
